# Generated by Django 5.0.1 on 2024-02-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.category"
            ),
        ),
    ]
